//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//

package de.galgtonold.jollydayandroid.config;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for Configuration complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Holidays" type="{http://www.example.org/Holiday}Holidays"/>
 *         &lt;element name="SubConfigurations" type="{http://www.example.org/Holiday}Configuration" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hierarchy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Root
@Namespace(prefix = "tns", reference = "http://www.example.org/Holiday")
public class Configuration {

	@Attribute(name = "schemaLocation", required=false)
	@Namespace(reference = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi")
	private String schemaLocation;

	@Element(name = "Holidays")
	protected Holidays holidays;
	@ElementList(entry="SubConfigurations", type=Configuration.class, inline=true, required=false)
	protected List<Configuration> subConfigurations;
	@Attribute
	protected String hierarchy;
	@Attribute
	protected String description;

	/**
	 * Gets the value of the holidays property.
	 * 
	 * @return possible object is {@link Holidays }
	 * 
	 */
	public Holidays getHolidays() {
		return holidays;
	}

	/**
	 * Sets the value of the holidays property.
	 * 
	 * @param value
	 *            allowed object is {@link Holidays }
	 * 
	 */
	public void setHolidays(Holidays value) {
		this.holidays = value;
	}

	/**
	 * Gets the value of the subConfigurations property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the subConfigurations property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubConfigurations().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Configuration }
	 * 
	 * 
	 */
	public List<Configuration> getSubConfigurations() {
		if (subConfigurations == null) {
			subConfigurations = new ArrayList<Configuration>();
		}
		return this.subConfigurations;
	}

	/**
	 * Gets the value of the hierarchy property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHierarchy() {
		return hierarchy;
	}

	/**
	 * Sets the value of the hierarchy property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHierarchy(String value) {
		this.hierarchy = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

}
