//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.galgtonold.jollydayandroid.config;

import org.simpleframework.xml.Attribute;


/**
 * <p>Java class for MovingCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MovingCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="substitute" type="{http://www.example.org/Holiday}Weekday" />
 *       &lt;attribute name="with" type="{http://www.example.org/Holiday}With" />
 *       &lt;attribute name="weekday" type="{http://www.example.org/Holiday}Weekday" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class MovingCondition {

	@Attribute
	protected Weekday substitute;
    @Attribute
    protected With with;
    @Attribute
    protected Weekday weekday;

    /**
     * Gets the value of the substitute property.
     * 
     * @return
     *     possible object is
     *     {@link Weekday }
     *     
     */
    public Weekday getSubstitute() {
        return substitute;
    }

    /**
     * Sets the value of the substitute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weekday }
     *     
     */
    public void setSubstitute(Weekday value) {
        this.substitute = value;
    }

    /**
     * Gets the value of the with property.
     * 
     * @return
     *     possible object is
     *     {@link With }
     *     
     */
    public With getWith() {
        return with;
    }

    /**
     * Sets the value of the with property.
     * 
     * @param value
     *     allowed object is
     *     {@link With }
     *     
     */
    public void setWith(With value) {
        this.with = value;
    }

    /**
     * Gets the value of the weekday property.
     * 
     * @return
     *     possible object is
     *     {@link Weekday }
     *     
     */
    public Weekday getWeekday() {
        return weekday;
    }

    /**
     * Sets the value of the weekday property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weekday }
     *     
     */
    public void setWeekday(Weekday value) {
        this.weekday = value;
    }

}
