//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.jollyday.config;

import org.simpleframework.xml.Attribute;



/**
 * <p>Java class for ChristianHoliday complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChristianHoliday">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Holiday}Holiday">
 *       &lt;attribute name="type" type="{http://www.example.org/Holiday}ChristianHolidayType" />
 *       &lt;attribute name="chronology" type="{http://www.example.org/Holiday}ChronologyType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class ChristianHoliday
    extends Holiday
{

    @Attribute
    protected ChristianHolidayType type;
    @Attribute(required=false)
    protected ChronologyType chronology;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ChristianHolidayType }
     *     
     */
    public ChristianHolidayType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChristianHolidayType }
     *     
     */
    public void setType(ChristianHolidayType value) {
        this.type = value;
    }

    /**
     * Gets the value of the chronology property.
     * 
     * @return
     *     possible object is
     *     {@link ChronologyType }
     *     
     */
    public ChronologyType getChronology() {
        return chronology;
    }

    /**
     * Sets the value of the chronology property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChronologyType }
     *     
     */
    public void setChronology(ChronologyType value) {
        this.chronology = value;
    }

}
