//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.jollyday.config;

import org.simpleframework.xml.Attribute;


/**
 * <p>Java class for EthiopianOrthodoxHoliday complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EthiopianOrthodoxHoliday">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Holiday}Holiday">
 *       &lt;attribute name="type" type="{http://www.example.org/Holiday}EthiopianOrthodoxHolidayType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class EthiopianOrthodoxHoliday
    extends Holiday
{

    @Attribute
    protected EthiopianOrthodoxHolidayType type;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EthiopianOrthodoxHolidayType }
     *     
     */
    public EthiopianOrthodoxHolidayType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EthiopianOrthodoxHolidayType }
     *     
     */
    public void setType(EthiopianOrthodoxHolidayType value) {
        this.type = value;
    }

}
