//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.jollyday.config;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;


/**
 * <p>Java class for FixedWeekdayBetweenFixed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FixedWeekdayBetweenFixed">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Holiday}Holiday">
 *       &lt;sequence>
 *         &lt;element name="from" type="{http://www.example.org/Holiday}Fixed"/>
 *         &lt;element name="to" type="{http://www.example.org/Holiday}Fixed"/>
 *       &lt;/sequence>
 *       &lt;attribute name="weekday" type="{http://www.example.org/Holiday}Weekday" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class FixedWeekdayBetweenFixed
    extends Holiday
{

    @Element
    protected Fixed from;
    @Element
    protected Fixed to;
    @Attribute
    protected Weekday weekday;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link Fixed }
     *     
     */
    public Fixed getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fixed }
     *     
     */
    public void setFrom(Fixed value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link Fixed }
     *     
     */
    public Fixed getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fixed }
     *     
     */
    public void setTo(Fixed value) {
        this.to = value;
    }

    /**
     * Gets the value of the weekday property.
     * 
     * @return
     *     possible object is
     *     {@link Weekday }
     *     
     */
    public Weekday getWeekday() {
        return weekday;
    }

    /**
     * Sets the value of the weekday property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weekday }
     *     
     */
    public void setWeekday(Weekday value) {
        this.weekday = value;
    }

}
