//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.jollyday.config;

import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;

/**
 * <p>Java class for MoveableHoliday complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MoveableHoliday">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Holiday}Holiday">
 *       &lt;sequence>
 *         &lt;element name="MovingCondition" type="{http://www.example.org/Holiday}MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public abstract class MoveableHoliday
    extends Holiday
{

    @ElementList(entry="MovingCondition", type=MovingCondition.class, inline=true, required=false)
    protected List<MovingCondition> movingCondition;

    /**
     * Gets the value of the movingCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movingCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovingCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MovingCondition }
     * 
     * 
     */
    public List<MovingCondition> getMovingCondition() {
        if (movingCondition == null) {
            movingCondition = new ArrayList<MovingCondition>();
        }
        return this.movingCondition;
    }

}
