//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.jollyday.config;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for RelativeToEasterSunday complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelativeToEasterSunday">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Holiday}Holiday">
 *       &lt;sequence>
 *         &lt;element name="chronology" type="{http://www.example.org/Holiday}ChronologyType"/>
 *         &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class RelativeToEasterSunday
    extends Holiday
{

    @Element
    protected ChronologyType chronology;
    protected int days;

    /**
     * Gets the value of the chronology property.
     * 
     * @return
     *     possible object is
     *     {@link ChronologyType }
     *     
     */
    public ChronologyType getChronology() {
        return chronology;
    }

    /**
     * Sets the value of the chronology property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChronologyType }
     *     
     */
    public void setChronology(ChronologyType value) {
        this.chronology = value;
    }

    /**
     * Gets the value of the days property.
     * 
     */
    public int getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     */
    public void setDays(int value) {
        this.days = value;
    }

}
