//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.jollyday.config;

/**
 * <p>Java class for Substituted.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Substituted">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ON_SATURDAY"/>
 *     &lt;enumeration value="ON_SUNDAY"/>
 *     &lt;enumeration value="ON_WEEKEND"/>
 *     &lt;enumeration value="ON_TUESDAY"/>
 *     &lt;enumeration value="ON_WEDNESDAY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum Substituted {

    ON_SATURDAY,
    ON_SUNDAY,
    ON_WEEKEND,
    ON_TUESDAY,
    ON_WEDNESDAY;

    public String value() {
        return name();
    }

    public static Substituted fromValue(String v) {
        return valueOf(v);
    }

}
