//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 12:42:28 AM MEZ 
//


package de.galgtonold.jollydayandroid.config;

import org.simpleframework.xml.Attribute;


/**
 * <p>Java class for Holiday complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Holiday">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="validFrom" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="validTo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="every" type="{http://www.example.org/Holiday}HolidayCycleType" default="EVERY_YEAR" />
 *       &lt;attribute name="descriptionPropertiesKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="localizedType" type="{http://www.example.org/Holiday}HolidayType" default="OFFICIAL_HOLIDAY" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public abstract class Holiday {

    @Attribute(required=false)
    protected Integer validFrom;
    @Attribute(required=false)
    protected Integer validTo;
    @Attribute(required=false)
    protected String every;
    @Attribute(required=false)
    protected String descriptionPropertiesKey;
    @Attribute(required=false)
    protected HolidayType localizedType;

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValidFrom(Integer value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValidTo(Integer value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the every property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvery() {
        if (every == null) {
            return "EVERY_YEAR";
        } else {
            return every;
        }
    }

    /**
     * Sets the value of the every property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvery(String value) {
        this.every = value;
    }

    /**
     * Gets the value of the descriptionPropertiesKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionPropertiesKey() {
        return descriptionPropertiesKey;
    }

    /**
     * Sets the value of the descriptionPropertiesKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionPropertiesKey(String value) {
        this.descriptionPropertiesKey = value;
    }

    /**
     * Gets the value of the localizedType property.
     * 
     * @return
     *     possible object is
     *     {@link HolidayType }
     *     
     */
    public HolidayType getLocalizedType() {
        if (localizedType == null) {
            return HolidayType.OFFICIAL_HOLIDAY;
        } else {
            return localizedType;
        }
    }

    /**
     * Sets the value of the localizedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HolidayType }
     *     
     */
    public void setLocalizedType(HolidayType value) {
        this.localizedType = value;
    }

}
